routes/web.php
<?php

Route::get('/spa', 'HomeController@spa')->name('spa');

Route::group(['middleware' => 'auth'], function(){
	Route::resource('terapias', 'TerapiaController');
	Route::resource('perfil', 'PerfilController');
	Route::resource('schedule', 'ScheduleController');
	Route::resource('atenciones', 'AtencionesController');
	Route::resource('comentarios', 'ComentariosController');
	Route::resource('user', 'UserController');
	Route::resource('palabras', 'PalabrasController');
	Route::resource('PalabrasTerapias', 'PalabrasTerapiasController');
	Route::resource('noticias', 'NoticiasController');
	Route::resource('solicitudes', 'SolicitudesController');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/home/{id}/', 'HomeController@show')->name('home.noticias');
	Route::get('/solicitudes/aprobar/{id}', 'SolicitudesController@aprobado')->name('admin.aprobar');
	Route::get('/solicitudes/rechazar/{id}', 'SolicitudesController@rechazado')->name('admin.rechazar');
	Route::post('/palabras/eliminar', 'PalabrasController@elimina')->name('palabras.elimina');
	Route::get('/SugerenciaTerapias', 'SugerenciaTerapiasController@index')->name('sugerenciaTerapias');
	Route::get('/terapias/anadir/{user}', 'TerapiaController@solicitarTerapia')->name('terapias.añadir');
	Route::post('/terapias/solicitar/{user}', 'TerapiaController@solicitar')->name('terapias.solicitar');
	Route::post('/terapias/sugerir/{user}', 'TerapiaController@sugerir')->name('terapias.sugerir');
	Route::get('/atenciones/ver/{user}', 'AtencionesController@verAtenciones')->name('atenciones.ver');
	// Route::get('/user/terapia/{id}', 'TerapiaController@userupdate')->name('terapia.userupdate');
	Route::get('/user/{id}/formulario', 'UserController@formulario')->name('user.formulario');
	Route::post('/user/{id}/solicitud-terapeuta', 'UserController@solicita')->name('user.solicita');
	Route::get('/user/descripcion/{id}', 'UserController@descripcion')->name('user.descripcion');
	Route::get('/user/descripcion/update/{id}', 'UserController@descripcionupdate')->name('user.descripcionupdate');
	Route::get('/comentarios/user/{id}/', 'ComentariosController@showuser')->name('comentarios.showuser');
	Route::get('/comentarios/terapeuta/{id}/', 'ComentariosController@showterapeuta')->name('comentarios.showterapeuta');
	Route::get('/notificaciones', 'NotificacionesController@index')->name('notificaciones');
	Route::get('/notificaciones/{id}/dismiss', 'NotificacionesController@dismiss')->name('notificaciones.dismiss');
	Route::get('/comentarios/user/crea/{id}', 'ComentariosController@comentar')->name('comentarios.comentar');
	Route::get('/comentarios/terapeuta/crea/{id}', 'ComentariosController@comentaterapeuta')->name('comentarios.comentaterapeuta');
	Route::post('/comentarios/user/store/{id}', 'ComentariosController@guardar')->name('comentarios.guardar');
	Route::post('/comentarios/terapeuta/store/{id}', 'ComentariosController@guardarterapeuta')->name('comentarios.guardarterapeuta');
});

Route::group(['prefix'=> 'admin','middleware' => 'auth'], function(){
	Route::get('/noticias/listar', 'NoticiasController@listar')->name('noticias.listar');
	Route::get('/terapias/listar', 'TerapiaController@listar')->name('terapias.listar');
	Route::get('/terapias/{id}', 'TerapiaController@muestra')->name('terapias.muestra');
	Route::get('/terapeutas/{id}', 'UserController@verterapeuta')->name('users.verterapeuta');
	Route::get('/terapeutas/edit/{id}', 'UserController@adminedit')->name('users.adminedit');
	Route::get('/terapeutas/update/{id}', 'UserController@adminupdate')->name('users.adminupdate');
	Route::get('/terapeutas/destroy/{id}', 'UserController@admindestroy')->name('users.admindestroy');
	Route::get('/terapeutas', 'AdminController@terapeutas')->name('admin.terapeutas');
	Route::get('/usuarios', 'AdminController@usuarios')->name('admin.usuarios');
	Route::get('/terapias', 'AdminController@terapias')->name('admin.terapias');
	Route::get('/user/{id}', 'UserController@show')->name('admin.user.show');
	Route::get('/palabras/terapias', 'AdminController@showPalabrasTerapias')->name('sintomas.index');
	Route::post('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/terapia/asignar/{id}', 'AdminController@verAgregaTerapia')->name('admin.verasigna');
	Route::post('/terapia/asigna/{id}', 'AdminController@AgregaTerapia')->name('admin.asigna');
});

Route::group(['prefix'=> 'perfil','middleware' => 'auth'], function(){
	Route::get('/{id}/comentarios', 'ComentariosController@show')->name('perfil.comentarios');
	Route::get('/{id}/terapias', 'TerapiaController@show')->name('perfil.terapias');
	Route::get('/{id}/horario', 'ScheduleController@show')->name('perfil.horario');
	Route::get('/{id}/agendamiento/{terapia}', 'AtencionesController@index')->name('perfil.hora');
	Route::get('/{id}/{terapia}', 'TerapiaController@ver')->name('perfil.miterapia');
});

Route::group(['prefix'=> 'search','middleware' => 'auth'], function(){
	Route::post('/','SearchController@index')->name('search');
	Route::get('/','SearchController@index')->name('search');
	Route::get('/terapia/{id}/show','SearchController@showterapia')->name('search.showterapia');
	Route::get('/terapeuta/{id}/show','PerfilController@show')->name('search.showterapeuta');
	Route::post('/sugerencia','SearchController@sugerencia')->name('search.sugerencia');
});

Auth::routes();

resources/views/perfiles/terapeuta/atenciones.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	@if(!$atenciones->isEmpty())
	  	@foreach($atenciones as $atencion)
	        <div class="row bg-secondary border rounded" style="margin-bottom: 5px; margin-right: 5px; margin-left: 5px;">
	    		<div class="col-3">
	    			<a href="{{route('search.showterapeuta', $atencion->Cliente)}}">
	    				<img src="/imagenes/usuarios/{{$atencion->Cliente->imagen}}" style="height: 100px; width: 100px;" alt="Terapeuta-{{$user->id}}" class="img-responsive rounded"/>
	    			</a>
	    		</div>
	    		<div class="col-9">
	    			<div class="col-12">
	    				<div class="row" style="color: #5F1961;">
	    					<div class="col-4">
	    						Terapia
	    					</div>
	    					<div class="col-8">
	    						{{ $atencion->Terapia->nombre }}
	    					</div>
	    				</div>
	    			</div>
	    			<div class="col-12">
	    				<div class="row text-texto">
	    					<div class="col-4">
	    						Cliente
	    					</div>
	    					<div class="col-8">
	    						{{ $atencion->Cliente->name }}
	    					</div>
	    				</div>
	    			</div>
	    			<div class="col-12">
	    				<div class="row text-texto">
	    					<div class="col-4">
	    						Hora
	    					</div>
	    					<div class="col-8">
	    						{{ $atencion->Horario->fecha }} {{ $atencion->Horario->hora }}
	    					</div>
	    				</div>
	    			</div>
	    			<div class="col-12">
	    				<div class="row text-texto">
	    					<div class="col-4">
	    						Precio
	    					</div>
	    					<div class="col-8">
	    						${{ $atencion->precio }}.-
	    					</div>
	    				</div>
	    			</div>
	    			<div class="col-12">
	    				<div class="row text-texto">
	    					<div class="col-4">
	    						Estado
	    					</div>
	    					<div class="col-8">
	    						{{ $atencion->estado }}
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    		<div class="col-12 col-lg-12 col-md-12 col-sm-12 col-xl-12 justify-content-center">
	    			<a href="{{ route('comentarios.comentaterapeuta',$atencion) }}" class="btn btn-md btn-block btn-success ">
	    				<i class="far fa-check-circle"></i> Dejar un comentario
	    			</a>
	    		</div>
	        </div>
		@endforeach
	@else
		<div class="card text-center">
	      	<div class="card-body">
	        	<h5 class="card-title">No tienes atenciones.</h5>
	      	</div>
    	</div>
	@endif
</div>

@endsection

resources/views/perfiles/terapeuta/comentarios.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

<div class="container">
	@if(count($comentarios) > 0)
		<div class="row justify-content-center">
		  	@foreach($comentarios as $comentario)
			  	<div class="col-12 col-sm-12 col-md-8 col-lg-8">
		  		    <div class="row bg-secondary border rounded" style="margin-bottom: 5px; margin-right: 5px; margin-left: 5px;">
		  				<div class="col-4 col-lg-4 col-md-4 col-sm-4">
		  					<img src="/imagenes/usuarios/{{$comentario->ComentariosUsuario->imagen}}" alt="Usuario-{{$comentario->ComentariosUsuario->id}}" class="rounded img-responsive" style="width: 120px; height: 120px;" />
		  				</div>
		  				<div class="col-8 col-lg-8 col-md-8 col-sm-8">
		  					<div class="col-12">
		  						<div class="row" style="color: #5F1961;">
		  							<div class="col-4">
		  								Cliente
		  							</div>
		  							<div class="col-8">
		  								{{ $comentario->ComentariosUsuario->name }}
		  							</div>
		  						</div>
		  					</div>
		  					<div class="col-12">
		  						<div class="row text-texto">
		  							<div class="col-4">
		  								Puntaje
		  							</div>
		  							<div class="col-8">
		  								{{ $comentario->puntaje }}
		  							</div>
		  						</div>
		  					</div>
		  					<div class="col-12">
		  						<div class="row text-texto">
		  							<div class="col-4">
		  								Comentario
		  							</div>
		  							<div class="col-8">
		  								{{ $comentario->comentario }}
		  							</div>
		  						</div>
		  					</div>
		  					<div class="col-12">
		  						<div class="row text-texto">
		  							<div class="col-4">
		  								Fecha
		  							</div>
		  							<div class="col-8">
		  								{{ $comentario->created_at->format('d-m-Y') }}
		  							</div>
		  						</div>
		  					</div>
		  				</div>
		  		    </div>
	  		    </div>
			@endforeach
		</div>
	@else
		<div class="card text-center">
	      	<div class="card-body">
	        	<h5 class="card-title">Este terapeuta todavia no cuenta con comentarios.</h5>
	      	</div>
    	</div>
	@endif
</div>

@endsection

resources/views/perfiles/terapeuta/evaluar.blade.php
@extends('layout')

@section('title', 'Evaluación')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Enviar un comentario!</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('comentarios.guardarterapeuta', $atencion) }}">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="terapeuta">Nombre del Cliente</label>
					<input 
						name="terapeuta" 
						type="terapeuta" 
						class="form-control" 
						id="terapeuta" 
						value="{{ $cliente->name }}"
						disabled
					>
				</div>
				<div class="form-group">
					<label for="terapia">Nombre de la Terapia</label>
					<input 
						name="terapia" 
						type="text" 
						class="form-control" 
						id="terapia" 
						value="{{ $terapia->nombre }}"
						disabled 
					>
				</div>
				<div class="form-group">
					<label for="horario">Fecha de la Atención</label>
					<input 
						name="horario" 
						type="text" 
						class="form-control" 
						id="horario" 
						value="{{ $horario->fecha }} - {{ $horario->hora }}"
						disabled
					>
				</div>
				<div class="form-group">
					<label for="precio">Precio de la Terapia</label>
					<input 
						name="precio" 
						type="number" 
						class="form-control" 
						id="precio" 
						value="{{ $atencion->precio }}"
						disabled
					>
				</div>
				<div class="form-group">
					<label for="comentario">Comentario</label>
					<input 
						name="comentario" 
						type="text" 
						class="form-control" 
						id="comentario" 
						placeholder="Ingresa un comentario" 
					>
				</div>
				<div class="form-group">
					<label for="puntaje">Puntaje</label>
						<div class="form-group required">
							<div class="col-sm-12" style="color: #EEE7F3;">
								<input class="star star-1" value="1" type="radio" id="star-1" name="star" style="display: none;" onclick="rate(1)" />
								<label class="star star-1" for="star-1"><span id="span-1" class="far fa-star fa-3x"></span></label>

								<input class="star star-2" value="2" type="radio" id="star-2" name="star" style="display: none;" onclick="rate(2)"/>
								<label class="star star-2" for="star-2"><span id="span-2" class="far fa-star fa-3x"></span></label>
								
								<input class="star star-3" value="3" type="radio" id="star-3" name="star" style="display: none;" onclick="rate(3)"/>
								<label class="star star-3" for="star-3"><span id="span-3" class="far fa-star fa-3x"></span></label>
								
								<input class="star star-4" value="4" type="radio" id="star-4" name="star" style="display: none;" onclick="rate(4)"/>
								<label class="star star-4" for="star-4"><span id="span-4" class="far fa-star fa-3x"></span></label>
								
								<input class="star star-5" value="5" type="radio" id="star-5" name="star" style="display: none;" onclick="rate(5)"/>
								<label class="star star-5" for="star-5"><span id="span-5" class="far fa-star fa-3x"></span></label>
							</div>
						</div>
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Enviar Comentario</button>
			</div>
		</form>
		<script type="text/javascript">
			function rate(id) {
				if (id == 1) {
					document.getElementById('span-1').style.color = '#BB5352';
					document.getElementById('span-2').style.color = '#EEE7F3';
					document.getElementById('span-3').style.color = '#EEE7F3';
					document.getElementById('span-4').style.color = '#EEE7F3';
					document.getElementById('span-5').style.color = '#EEE7F3';
				} else if (id == 2) {
					document.getElementById('span-1').style.color = '#BB5352';
					document.getElementById('span-2').style.color = '#BB5352';
					document.getElementById('span-3').style.color = '#EEE7F3';
					document.getElementById('span-4').style.color = '#EEE7F3';
					document.getElementById('span-5').style.color = '#EEE7F3';
				} else if (id == 3) {
					document.getElementById('span-1').style.color = '#BB5352';
					document.getElementById('span-2').style.color = '#BB5352';
					document.getElementById('span-3').style.color = '#BB5352';
					document.getElementById('span-4').style.color = '#EEE7F3';
					document.getElementById('span-5').style.color = '#EEE7F3';
				} else if (id == 4) {
					document.getElementById('span-1').style.color = '#BB5352';
					document.getElementById('span-2').style.color = '#BB5352';
					document.getElementById('span-3').style.color = '#BB5352';
					document.getElementById('span-4').style.color = '#BB5352';
					document.getElementById('span-5').style.color = '#EEE7F3';
				} else if (id == 5) {
					document.getElementById('span-1').style.color = '#BB5352';
					document.getElementById('span-2').style.color = '#BB5352';
					document.getElementById('span-3').style.color = '#BB5352';
					document.getElementById('span-4').style.color = '#BB5352';
					document.getElementById('span-5').style.color = '#BB5352';
				}
			}
		</script>
	</div>
</div>

@endsection

resources/views/perfiles/terapeuta/solicitaTerapia.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Solicitar una Terapia Existente</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('terapias.solicitar', $user) }}">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="terapia">Terapias</label>
					<select
						name="terapia"
						class="form-control"
						id="terapia" 
					>
						<option>Seleccione una Terapia</option>
						@foreach($terapias as $terapia)
							@if (!$user->TerapiasUser->keyBy('terapias_id')->has($terapia->id))
						    	<option value="{{$terapia->id}}">{{ $terapia->nombre}}</option>
							@endif
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label for="descripcion">Descripción</label><br>
					<input 
						name="descripcion" 
						type="text" 
						class="form-control" 
						id="descripcion"
						placeholder="Ingresa una descripción de tu solicitud" 
					>
				</div>
				<div class="form-group">
					<label for="precio">Precio de la Terapia</label>
					<input 
						name="precio" 
						type="number" 
						class="form-control" 
						id="precio" 
						placeholder="Ingresa el precio de la Terapia" 
						required 
					>
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Solicitar</button>
			</div>
		</form>
		<hr>
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Solicitar una Nueva Terapia</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('terapias.sugerir', $user) }}">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="nombre">Nombre de la Terapia</label>
					<input 
						name="nombre" 
						type="text" 
						class="form-control" 
						id="nombre" 
						placeholder="Ingresa el nombre de la Terapia" 
						required
					>
				</div>
				<div class="form-group">
					<label for="descripcion">Descripción de la Terapia</label>
					<input 
						name="descripcion" 
						type="text" 
						class="form-control" 
						id="descripcion" 
						placeholder="Ingresa la descripción de la Terapia" 
						required
					>
				</div>
				<div class="form-group">
					<label for="precio">Precio de la Terapia</label>
					<input 
						name="precio" 
						type="number" 
						class="form-control" 
						id="precio" 
						placeholder="Ingresa el precio de la Terapia" 
						required
					>
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Solicitar</button>
			</div>
		</form>
	</div>
</div>

@endsection

resources/views/perfiles/terapeuta/terapias.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

<div class="container">
	@if(count($user->User) > 0)
	  	@foreach($user->User as $terapias)
			{{-- <a href="{{ (auth()->user()->id == $user->id) ? route('perfil.miterapia', ['id' => $user->id, 'terapia' => $terapias->id]) : route('perfil.hora', ['id' => $user->id, 'terapia' => $terapias->id])}}"> --}}
			@if (auth()->user()->id == $user->id)
			    <div class="card text-center border bg-secondary">
			      	<div class="card-body">
			        	<h5 class="card-title text-primary">{{ $terapias->nombre }}</h5>
			        	<p class="card-text text-truncate text-primary">
			        		{{$terapias->descripcion}}
			        	</p>
			      	</div>
			    </div>
			@else
				<a href="{{ route('perfil.hora', ['id' => $user->id, 'terapia' => $terapias->id]) }}">
				    <div class="card text-center border bg-secondary" style="margin-bottom: 10px;">
				      	<div class="container" >
				      		<div class="row">
				      			<div class="col-2" style="padding-left: 0px; padding-right: 0px;">
				      				@if(isset($terapias->imagen))
				      					<img src="/imagenes/terapias/{{$terapias->imagen}}" alt="Terapia-{{$terapias->id}}" class="card-img-top rounded img-fluid"/>
				      				@else
				      					<img src="/imagenes/terapias/default.jpg" alt="Terapia-{{$terapias->id}}" class="card-img-top rounded img-fluid"/>
				      				@endif
				      			</div>
				      			<div class="col-10">
				      				<div class="row">
				      					<div class="col-12 bg-primary" style="color: #EEE7F3; text-align: left;">
				      						<h5 class="card-title">{{ $terapias->nombre }}</h5>
				      					</div>
				      					<div class="col-12">
				      						<p class="card-text text-truncate">
				      							{{$terapias->descripcion}}
				      						</p>
				      					</div>
				      				</div>
				      			</div>
				      		</div>
{{-- 				        	<h5 class="card-title">{{ $terapias->nombre }}</h5>
				        	<p class="card-text text-truncate">
				        		{{$terapias->descripcion}}
				        	</p> --}}
				      	</div>
				    </div>
				</a>
			@endif
		@endforeach
	@else
		<div class="card text-center">
	      	<div class="card-body">
	        	<h5 class="card-title">Este terapeuta todavia no cuenta con terapias para impartir.</h5>
	      	</div>
    	</div>
	@endif
</div>

@endsection

resources/views/perfiles/terapeuta/tomahora.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

<div class="container">
	
	<div class="box box-warning">
		<div class="box-header with-border">
			<h3 class="box-title">Selecciona una Hora</h3>
		</div>
		<div class="box-body">
			<form role="form" method="POST" action="{{ route('atenciones.store') }}">
				@csrf
				<div class="form-group">
					<label>Terapeuta</label>
					<input type="text" class="form-control" value="{{ $user->name }}" disabled>
					<input type="text" class="form-control" name="terapeuta" hidden value="{{ $user->id }}">
				</div>
				<div class="form-group">
					<label>Terapia</label>
					<input type="text" class="form-control" value="{{ $terapia->nombre }}" disabled>
					<input type="text" class="form-control" name="terapia" hidden value="{{ $terapia->id }}">
				</div>
				<div class="form-group">
					<label>Precio</label>
					@foreach($user->User as $pivot)
						@if($pivot->pivot->terapias_id == $terapia->id)
							<input type="text" class="form-control" value="{{ $pivot->pivot->precio }}" disabled>
							<input type="text" class="form-control" name="precio" hidden value="{{ $pivot->pivot->precio }}">
						@endif
					@endforeach
				</div>
				<div class="form-group">
					<label>Horas</label>
					@if(isset($error))
						<div class="container alert alert-danger alert-dismissible">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							<h4><i class="fas fa-times"></i> {{ $error }}</h4>
						</div>
					@endif
					<select class="form-control" name="hora">
						<option>Selecciona una hora</option>
						@foreach($horas as $hora)
							<option value="{{$hora->id}}">{{ $hora->fecha . " - " . $hora->hora }}</option>
						@endforeach
					</select>
				</div>
				<div class="box-footer">
					<button type="submit" class="btn btn-primary">Solicitar Hora</button>
				</div>
			</form>
		</div>
	</div>

</div>

@endsection

resources/views/perfiles/terapeuta/verterapia.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Añadir una descripcion propia para la terapia.</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('terapia.userupdate', $terapia) }}">
			{{ method_field('GET') }}
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="terapia">Terapia</label>
					<input 
						name="terapia" 
						type="text" 
						class="form-control" 
						id="terapia" 
						value="{{ $terapia->nombre }}"
						disabled
					>
				</div>
				<div class="form-group">
					<label for="descripcion">Descripción</label>
					<textarea  
						name="descripcion" 
						type="text"
						cols="40" 
       					rows="5" 
						class="form-control" 
						id="descripcion"
						required 
					>
					{{($user->TerapiasUser->where('terapias_id', $terapia->id)[0]->descripcion == "") ? $terapia->descripcion : $user->TerapiasUser->where('terapias_id', $terapia->id)[0]->descripcion }}
					</textarea>
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Actualizar</button>
			</div>
		</form>
	</div>
</div>


@endsection