routes/web.php
<?php

Route::get('/spa', 'HomeController@spa')->name('spa');

Route::group(['middleware' => 'auth'], function(){
	Route::resource('terapias', 'TerapiaController');
	Route::resource('perfil', 'PerfilController');
	Route::resource('schedule', 'ScheduleController');
	Route::resource('atenciones', 'AtencionesController');
	Route::resource('comentarios', 'ComentariosController');
	Route::resource('user', 'UserController');
	Route::resource('palabras', 'PalabrasController');
	Route::resource('PalabrasTerapias', 'PalabrasTerapiasController');
	Route::resource('noticias', 'NoticiasController');
	Route::resource('solicitudes', 'SolicitudesController');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/home/{id}/', 'HomeController@show')->name('home.noticias');
	Route::get('/solicitudes/aprobar/{id}', 'SolicitudesController@aprobado')->name('admin.aprobar');
	Route::get('/solicitudes/rechazar/{id}', 'SolicitudesController@rechazado')->name('admin.rechazar');
	Route::post('/palabras/eliminar', 'PalabrasController@elimina')->name('palabras.elimina');
	Route::get('/SugerenciaTerapias', 'SugerenciaTerapiasController@index')->name('sugerenciaTerapias');
	Route::get('/terapias/anadir/{user}', 'TerapiaController@solicitarTerapia')->name('terapias.añadir');
	Route::post('/terapias/solicitar/{user}', 'TerapiaController@solicitar')->name('terapias.solicitar');
	Route::post('/terapias/sugerir/{user}', 'TerapiaController@sugerir')->name('terapias.sugerir');
	Route::get('/atenciones/ver/{user}', 'AtencionesController@verAtenciones')->name('atenciones.ver');
	// Route::get('/user/terapia/{id}', 'TerapiaController@userupdate')->name('terapia.userupdate');
	Route::get('/user/{id}/formulario', 'UserController@formulario')->name('user.formulario');
	Route::post('/user/{id}/solicitud-terapeuta', 'UserController@solicita')->name('user.solicita');
	Route::get('/user/descripcion/{id}', 'UserController@descripcion')->name('user.descripcion');
	Route::get('/user/descripcion/update/{id}', 'UserController@descripcionupdate')->name('user.descripcionupdate');
	Route::get('/comentarios/user/{id}/', 'ComentariosController@showuser')->name('comentarios.showuser');
	Route::get('/comentarios/terapeuta/{id}/', 'ComentariosController@showterapeuta')->name('comentarios.showterapeuta');
	Route::get('/notificaciones', 'NotificacionesController@index')->name('notificaciones');
	Route::get('/notificaciones/{id}/dismiss', 'NotificacionesController@dismiss')->name('notificaciones.dismiss');
	Route::get('/comentarios/user/crea/{id}', 'ComentariosController@comentar')->name('comentarios.comentar');
	Route::get('/comentarios/terapeuta/crea/{id}', 'ComentariosController@comentaterapeuta')->name('comentarios.comentaterapeuta');
	Route::post('/comentarios/user/store/{id}', 'ComentariosController@guardar')->name('comentarios.guardar');
	Route::post('/comentarios/terapeuta/store/{id}', 'ComentariosController@guardarterapeuta')->name('comentarios.guardarterapeuta');
});

Route::group(['prefix'=> 'admin','middleware' => 'auth'], function(){
	Route::get('/noticias/listar', 'NoticiasController@listar')->name('noticias.listar');
	Route::get('/terapias/listar', 'TerapiaController@listar')->name('terapias.listar');
	Route::get('/terapias/{id}', 'TerapiaController@muestra')->name('terapias.muestra');
	Route::get('/terapeutas/{id}', 'UserController@verterapeuta')->name('users.verterapeuta');
	Route::get('/terapeutas/edit/{id}', 'UserController@adminedit')->name('users.adminedit');
	Route::get('/terapeutas/update/{id}', 'UserController@adminupdate')->name('users.adminupdate');
	Route::get('/terapeutas/destroy/{id}', 'UserController@admindestroy')->name('users.admindestroy');
	Route::get('/terapeutas', 'AdminController@terapeutas')->name('admin.terapeutas');
	Route::get('/usuarios', 'AdminController@usuarios')->name('admin.usuarios');
	Route::get('/terapias', 'AdminController@terapias')->name('admin.terapias');
	Route::get('/user/{id}', 'UserController@show')->name('admin.user.show');
	Route::get('/palabras/terapias', 'AdminController@showPalabrasTerapias')->name('sintomas.index');
	Route::post('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/terapia/asignar/{id}', 'AdminController@verAgregaTerapia')->name('admin.verasigna');
	Route::post('/terapia/asigna/{id}', 'AdminController@AgregaTerapia')->name('admin.asigna');
});

Route::group(['prefix'=> 'perfil','middleware' => 'auth'], function(){
	Route::get('/{id}/comentarios', 'ComentariosController@show')->name('perfil.comentarios');
	Route::get('/{id}/terapias', 'TerapiaController@show')->name('perfil.terapias');
	Route::get('/{id}/horario', 'ScheduleController@show')->name('perfil.horario');
	Route::get('/{id}/agendamiento/{terapia}', 'AtencionesController@index')->name('perfil.hora');
	Route::get('/{id}/{terapia}', 'TerapiaController@ver')->name('perfil.miterapia');
});

Route::group(['prefix'=> 'search','middleware' => 'auth'], function(){
	Route::post('/','SearchController@index')->name('search');
	Route::get('/','SearchController@index')->name('search');
	Route::get('/terapia/{id}/show','SearchController@showterapia')->name('search.showterapia');
	Route::get('/terapeuta/{id}/show','PerfilController@show')->name('search.showterapeuta');
	Route::post('/sugerencia','SearchController@sugerencia')->name('search.sugerencia');
});

Auth::routes();

app/Http/Controllers/ScheduleController.php
<?php

namespace App\Http\Controllers;

use App\Horarios;
use App\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class ScheduleController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usuario = auth()->user();

        $array['user'] = $usuario;

        if (request()->wantsJson() ) {
            return $array;
        }

        return view('schedule.index',[
            'user' => $usuario,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()->user();
        $h = 9;
        while ($h < 21) {
            $key = date('H:i', strtotime(date('Y-m-d') . ' + ' . $h . ' hours'));
            $value = date('H:i', strtotime(date('Y-m-d') . ' + ' . $h . ' hours'));
            $horas[$key] = $value;
            $h++;
        }

        $hoy = Carbon::now()->setTimezone('America/Santiago');
        // $hoy = Carbon::now();
        if ($hoy->isMonday()) {
            $hoy->addDays(7);
        } elseif ($hoy->isTuesday()) {
            $hoy->addDays(6);
        } elseif ($hoy->isWednesday()) {
            $hoy->addDays(5);
        } elseif ($hoy->isThursday()) {
            $hoy->addDays(4);
        } elseif ($hoy->isFriday()) {
            $hoy->addDays(3);
        } elseif ($hoy->isSaturday()) {
            $hoy->addDays(2);
        } elseif ($hoy->isSunday()) {
            $hoy->addDays(1);
        } else {
            $mensaje = 'Aún no puedes crear tu siguiente horario de trabajo.';

            $array['user'] = $user;
            $array['mensaje'] = $mensaje;

            if (request()->wantsJson() ) {
                return $array;
            }

            return view('schedule.create',[
                'user' => $user,
                'mensaje' => $mensaje,
            ]);
        }

        $ultimodia = Horarios::where('semana', $hoy->weekOfYear)->where('año', $hoy->weekYear)->where('user_id', $user->id)->get();
        if (!$ultimodia->isEmpty()) {
            $mensaje = "Ya haz creado el horario de trabajo de la siguiente semana, si quieres editarlo ve a la opción 'Editar'.";

            $array['user'] = $user;
            $array['mensaje'] = $mensaje;

            if (request()->wantsJson() ) {
                return $array;
            }

            return view('schedule.create',[
                'user' => $user,
                'mensaje' => $mensaje,
            ]);
        }

        for ($i=1; $i <= 7; $i++) { 
            $dia[$i] = $hoy->format('d-m-Y');
            $hoy->addDay();
        }
        
        $array['horas'] = $horas;
        $array['dia'] = $dia;
        $array['user'] = $user;

        if (request()->wantsJson() ) {
            return $array;
        }

        return view('schedule.create',[
            'horas' => $horas,
            'dia' => $dia,
            'user' => $user,
        ]);
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        $recuest = $request->except(['_token']);
        $collection = collect($recuest);
        $hoy = Carbon::createFromFormat('Y-m-d', '2019-01-01', 'America/Santiago');
        foreach ($collection as $key => $value) {
            foreach ($value as $hora) {
                Horarios::create([
                    'user_id'       => $user->id,
                    'semana'        => $hoy->carbonize($key)->weekOfYear,
                    'año'           => $hoy->carbonize($key)->year,
                    'fecha'         => $hoy->carbonize($key),
                    'hora'          => $hora,
                    'estado'        => 'Disponible'
                ]);
            }
        }
        
        $mensaje = 'Calendario creado exitosamente';

        $array['user'] = $user;
        $array['mensaje'] = $mensaje;

        if (request()->wantsJson() ) {
            return $array;
        }

        return view('schedule.index',[
            'user' => $user,
            'mensaje' => $mensaje,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $horario = Horarios::where('user_id', $id)
            ->where('semana', Carbon::now()->setTimezone('America/Santiago')->weekOfYear)
            ->where('año', Carbon::now()->setTimezone('America/Santiago')->weekYear)
            ->get();

        $h = 9;
        while ($h < 21) {
            $key = date('H:i:s', strtotime(date('Y-m-d') . ' + ' . $h . ' hours'));
            $value = date('H:i:s', strtotime(date('Y-m-d') . ' + ' . $h . ' hours'));
            $horas[$key] = $value;
            $h++;
        }

        $hoy = Carbon::now()->setTimezone('America/Santiago')->startOfWeek();
        
        for ($i=1; $i <= 7; $i++) { 
            $dia[$i] = $hoy->format('d-m-Y');
            $hoy->addDay();
        }

        $var = [];
        foreach ($horario as $key => $value) {
            $x = date('d-m-Y', strtotime($value->fecha)) . "|" . $value->hora;
            $var[$x] = $value->id;
        }

        $var = collect($var);

        $horario = $horario->keyBy(function ($item) {
            return date('d-m-Y', strtotime($item['fecha'])) . '|' . $item['hora'];
        });

        $user = User::find($id);
        $mensaje = "Este terapeuta no tiene horario todavia";

        $array['horarios'] = $horario;
        $array['var'] = $var;
        $array['user'] = $user;
        $array['horas'] = $horas;
        $array['dias'] = $dia;
        $array['mensaje'] = $mensaje;

        if (request()->wantsJson() ) {
            return $array;
        }

        return view('schedule.show',[
            'horarios' => $horario,
            'var' => $var,
            'user' => $user,
            'horas' => $horas,
            'dias' => $dia,
            'mensaje' => $mensaje,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = auth()->user();

        $array['user'] = $user;

        if (request()->wantsJson() ) {
            return $array;
        }

        return view('schedule.update',[
            'user' => $user,
        ]);
    }

}

resources/views/schedule/create.blade.php
@extends('layout')

@section('title', 'Horario')

@section('content')

@if(isset($horas) || isset($dia))
	<div class="container p-2">
		<form method="POST" action="{{ route('schedule.store')}}">
			{{ csrf_field() }}
			<div class="box-header with-border text-center">
				<h3 class="box-title">Ingresar Horario</h3>
			</div>
			<div class="row">
				<div class="col-12">
					@foreach($dia as $d)
						<div class="row border p-2">
							<div class="col-lg-2 col-md-2 col-sm-12 text-center">
								<p>{{ $d }}</p>
							</div>
							<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
								<div class="row d-flex justify-content-between">
									@foreach($horas as $hora)
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 rounded border" style="margin-bottom: 2px; margin-right: 2px; width: auto;" id="label-{{ $d }}.{{ $hora }}" >
											<input id="{{ $d }}.{{ $hora }}" onclick="isChecked('{{ $d }}.{{ $hora }}');" style="display: none;" class="icheckbox_flat-green" type="checkbox" value="{{ $hora }}" name="{{ $d }}[]">
											<label class="form-check-label" for="{{ $d }}.{{ $hora }}">{{ $hora }}</label>
										</div>
									@endforeach
								</div>
							</div>
						</div>
					@endforeach
				</div>
				<input type="submit" class="btn btn-primary" value="Ingresar"> 
			</div>
		</form>
	</div>
@else
	<div class="container-fluid p-3">
		<div class="card text-center bg-secondary">
	      	<div class="card-body">
	        	<h5 class="card-title">{{ $mensaje }}</h5>
	      	</div>
	      	<a href="{{ route('schedule.index') }}">Volver</a>
		</div>
	</div>
@endif
<script type="text/javascript">
	function isChecked(id) {
		var checkbox = document.getElementById(id);
		var	div = document.getElementById('label-' + id);
		// alert(checkbox);
		if (checkbox.checked == true) {
			// alert(label);
			div.style.backgroundColor = "green";
			div.style.color = "white";
		} else {
			div.style.backgroundColor = "white";
			div.style.color = "black";
		}
	}
</script>
@endsection

resources/views/schedule/index.blade.php
@extends('layout')

@section('title', 'Horario')

@section('content')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container text-center">
	<a href="{{ route('perfil.horario', auth()->user()->id) }}">Ver mi calendario.</a><br>
	<a href="{{ route('schedule.create') }}">Crear mi calendario.</a><br>
	<a href="{{-- {{ route('schedule.update') }} --}}">Modificar mi calendario.</a><br>
</div>


@endsection

resources/views/schedule/show.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

<div class="container">
	@if(isset($horarios))
		<div class="container p-2">
			<div class="box-header with-border text-center">
				<h3 class="box-title">Horario</h3>
				<div>
					<span style="background-color: green; width: 5px; height: 5px;"></span>
					<small>En color verde las horas disponibles!</small>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					@foreach($dias as $d)
						<div class="row border p-2">
							<div class="col-lg-2 col-md-2 col-sm-12 text-center">
								<p>{{ $d }}</p>
							</div>
							<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
								<div class="row d-flex justify-content-left">
									@foreach($horas as $hora)
										{{-- {{dd($horarios)}} --}}
										@if ($horarios->has([$d . "|" . $hora]))
											<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 rounded border" style="margin-bottom: 2px; margin-right: 2px; width: auto; background-color: #CEF2B8;">
												<label class="form-check-label">{{ $hora }}</label>
											</div>
										@else
											<div class="col-lg-2 col-md-2 col-sm-4 col-xs-4 rounded border" style="margin-bottom: 2px; margin-right: 2px; width: auto;">
												<label class="form-check-label">{{ $hora }}</label>
											</div>
										@endif
									@endforeach
								</div>
							</div>
						</div>
					@endforeach
				</div>
			</div>
		</div>
	@else
		<div class="container-fluid p-3">
			<div class="card text-center">
		      	<div class="card-body">
		        	<h5 class="card-title">{{ $mensaje }}</h5>
		      	</div>
		      	<a href="{{ route('schedule.index') }}">Volver</a>
			</div>
		</div>
	@endif

</div>

@endsection

resources/views/schedule/update.blade.php
@extends('layout')

@section('title', 'Horario')

@section('content')

<div class="container">
	update horario
</div>


@endsection