routes/web.php
<?php

Route::get('/spa', 'HomeController@spa')->name('spa');

Route::group(['middleware' => 'auth'], function(){
	Route::resource('terapias', 'TerapiaController');
	Route::resource('perfil', 'PerfilController');
	Route::resource('schedule', 'ScheduleController');
	Route::resource('atenciones', 'AtencionesController');
	Route::resource('comentarios', 'ComentariosController');
	Route::resource('user', 'UserController');
	Route::resource('palabras', 'PalabrasController');
	Route::resource('PalabrasTerapias', 'PalabrasTerapiasController');
	Route::resource('noticias', 'NoticiasController');
	Route::resource('solicitudes', 'SolicitudesController');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/home/{id}/', 'HomeController@show')->name('home.noticias');
	Route::get('/solicitudes/aprobar/{id}', 'SolicitudesController@aprobado')->name('admin.aprobar');
	Route::get('/solicitudes/rechazar/{id}', 'SolicitudesController@rechazado')->name('admin.rechazar');
	Route::post('/palabras/eliminar', 'PalabrasController@elimina')->name('palabras.elimina');
	Route::get('/SugerenciaTerapias', 'SugerenciaTerapiasController@index')->name('sugerenciaTerapias');
	Route::get('/terapias/anadir/{user}', 'TerapiaController@solicitarTerapia')->name('terapias.añadir');
	Route::post('/terapias/solicitar/{user}', 'TerapiaController@solicitar')->name('terapias.solicitar');
	Route::post('/terapias/sugerir/{user}', 'TerapiaController@sugerir')->name('terapias.sugerir');
	Route::get('/atenciones/ver/{user}', 'AtencionesController@verAtenciones')->name('atenciones.ver');
	// Route::get('/user/terapia/{id}', 'TerapiaController@userupdate')->name('terapia.userupdate');
	Route::get('/user/{id}/formulario', 'UserController@formulario')->name('user.formulario');
	Route::post('/user/{id}/solicitud-terapeuta', 'UserController@solicita')->name('user.solicita');
	Route::get('/user/descripcion/{id}', 'UserController@descripcion')->name('user.descripcion');
	Route::get('/user/descripcion/update/{id}', 'UserController@descripcionupdate')->name('user.descripcionupdate');
	Route::get('/comentarios/user/{id}/', 'ComentariosController@showuser')->name('comentarios.showuser');
	Route::get('/comentarios/terapeuta/{id}/', 'ComentariosController@showterapeuta')->name('comentarios.showterapeuta');
	Route::get('/notificaciones', 'NotificacionesController@index')->name('notificaciones');
	Route::get('/notificaciones/{id}/dismiss', 'NotificacionesController@dismiss')->name('notificaciones.dismiss');
	Route::get('/comentarios/user/crea/{id}', 'ComentariosController@comentar')->name('comentarios.comentar');
	Route::get('/comentarios/terapeuta/crea/{id}', 'ComentariosController@comentaterapeuta')->name('comentarios.comentaterapeuta');
	Route::post('/comentarios/user/store/{id}', 'ComentariosController@guardar')->name('comentarios.guardar');
	Route::post('/comentarios/terapeuta/store/{id}', 'ComentariosController@guardarterapeuta')->name('comentarios.guardarterapeuta');
});

Route::group(['prefix'=> 'admin','middleware' => 'auth'], function(){
	Route::get('/noticias/listar', 'NoticiasController@listar')->name('noticias.listar');
	Route::get('/terapias/listar', 'TerapiaController@listar')->name('terapias.listar');
	Route::get('/terapias/{id}', 'TerapiaController@muestra')->name('terapias.muestra');
	Route::get('/terapeutas/{id}', 'UserController@verterapeuta')->name('users.verterapeuta');
	Route::get('/terapeutas/edit/{id}', 'UserController@adminedit')->name('users.adminedit');
	Route::get('/terapeutas/update/{id}', 'UserController@adminupdate')->name('users.adminupdate');
	Route::get('/terapeutas/destroy/{id}', 'UserController@admindestroy')->name('users.admindestroy');
	Route::get('/terapeutas', 'AdminController@terapeutas')->name('admin.terapeutas');
	Route::get('/usuarios', 'AdminController@usuarios')->name('admin.usuarios');
	Route::get('/terapias', 'AdminController@terapias')->name('admin.terapias');
	Route::get('/user/{id}', 'UserController@show')->name('admin.user.show');
	Route::get('/palabras/terapias', 'AdminController@showPalabrasTerapias')->name('sintomas.index');
	Route::post('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/terapia/asignar/{id}', 'AdminController@verAgregaTerapia')->name('admin.verasigna');
	Route::post('/terapia/asigna/{id}', 'AdminController@AgregaTerapia')->name('admin.asigna');
});

Route::group(['prefix'=> 'perfil','middleware' => 'auth'], function(){
	Route::get('/{id}/comentarios', 'ComentariosController@show')->name('perfil.comentarios');
	Route::get('/{id}/terapias', 'TerapiaController@show')->name('perfil.terapias');
	Route::get('/{id}/horario', 'ScheduleController@show')->name('perfil.horario');
	Route::get('/{id}/agendamiento/{terapia}', 'AtencionesController@index')->name('perfil.hora');
	Route::get('/{id}/{terapia}', 'TerapiaController@ver')->name('perfil.miterapia');
});

Route::group(['prefix'=> 'search','middleware' => 'auth'], function(){
	Route::post('/','SearchController@index')->name('search');
	Route::get('/','SearchController@index')->name('search');
	Route::get('/terapia/{id}/show','SearchController@showterapia')->name('search.showterapia');
	Route::get('/terapeuta/{id}/show','PerfilController@show')->name('search.showterapeuta');
	Route::post('/sugerencia','SearchController@sugerencia')->name('search.sugerencia');
});

Auth::routes();

resources/views/perfiles/admin/palabras_clave/asignar.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Asignar Palabras a una Terapia</h3>
		</div>
		<form role="form" method="POST" action="{{ route('admin.palabras') }}">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="terapia">Terapias</label>
					<select
						name="terapia"
						class="form-control"
						id="terapia" 
					>
						<option value="0">Seleccione una Terapia</option>
						@foreach($terapias as $terapia)
						    <option value="{{$terapia->id}}"> {{ $terapia->nombre }}</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label for="palabra">Palabras</label>
					<select
						name="palabra"
						class="form-control"
						id="palabra" 
					>
						<option value="0">Seleccione una Palabra</option>
						@foreach($palabras as $palabra)
						    <option value="{{$palabra->id}}"> {{ $palabra->palabra }}</option>
						@endforeach
					</select>
				</div>
			</div>
			<div class="box-footer">
				<button type="submit" class="btn btn-success">Asignar Palabras</button>
				<a class="btn btn-secondary" href="javascript:history.back()">Volver</a>
			</div>
		</form>
	</div>
</div>

@endsection

resources/views/perfiles/admin/palabras_clave/create_palabras.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="col-lg-6 col-sm-12 col-md-12">
				<div class="col-12">
					<div class="box-header with-border">
						<h3 class="box-title">Agregar una Palabra</h3>
					</div>
					<form role="form" method="POST" action="{{ route('palabras.store') }}">
						{{ csrf_field() }}
						<div class="box-body">
							<div class="form-group">
								<label for="palabra">Palabra</label>
								<input 
									name="palabra" 
									type="text" 
									class="form-control" 
									id="palabra"
									placeholder="Ingresa la Palabra Clave"
									required
								>
							</div>
						</div>
						<div class="box-footer">
							<button type="submit" class="btn btn-success">Añadir Palabra</button>
						</div>
					</form>
				</div>
				<hr>
				<div class="col-12">
					<div class="box-header with-border">
						<h3 class="box-title">Eliminar una Palabra</h3>
					</div>
					<form role="form" method="POST" action="{{ route('palabras.elimina') }}">
						{{ csrf_field() }} 
						<div class="box-body">
							<div class="form-group">
								<label for="palabra">Palabra</label>
								<select
									name="palabra"
									class="form-control"
									id="palabra" 
								>
									<option value="0">Seleccione una palabra</option>
									@foreach($palabras as $palabra)
									    <option value="{{$palabra->id}}"> {{ $palabra->palabra }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="box-footer">
							<button type="submit" class="btn btn-danger">Eliminar Palabra</button>
						</div>
					</form>
				</div>
			</div>
			<div class="col-lg-6 col-sm-12 col-md-12" style="margin-bottom: 100px;">
				<h4>Palabras Actuales en Sistema</h4>
				<div class="box-footer">
					<ul id="theList" class="d-flex justify-content-start row" style="padding-left: 5px;list-style-type: none; margin-right: 0px;">
						@foreach ($palabras as $palabra)
							<li class="tagitem col-sm-6 col-6 col-md-4 col-lg-3 col-xl-3">{{ $palabra->palabra }}</li>
						@endforeach
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection