routes/web.php
<?php

Route::get('/spa', 'HomeController@spa')->name('spa');

Route::group(['middleware' => 'auth'], function(){
	Route::resource('terapias', 'TerapiaController');
	Route::resource('perfil', 'PerfilController');
	Route::resource('schedule', 'ScheduleController');
	Route::resource('atenciones', 'AtencionesController');
	Route::resource('comentarios', 'ComentariosController');
	Route::resource('user', 'UserController');
	Route::resource('palabras', 'PalabrasController');
	Route::resource('PalabrasTerapias', 'PalabrasTerapiasController');
	Route::resource('noticias', 'NoticiasController');
	Route::resource('solicitudes', 'SolicitudesController');
});

Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/home/{id}/', 'HomeController@show')->name('home.noticias');
	Route::get('/solicitudes/aprobar/{id}', 'SolicitudesController@aprobado')->name('admin.aprobar');
	Route::get('/solicitudes/rechazar/{id}', 'SolicitudesController@rechazado')->name('admin.rechazar');
	Route::post('/palabras/eliminar', 'PalabrasController@elimina')->name('palabras.elimina');
	Route::get('/SugerenciaTerapias', 'SugerenciaTerapiasController@index')->name('sugerenciaTerapias');
	Route::get('/terapias/anadir/{user}', 'TerapiaController@solicitarTerapia')->name('terapias.añadir');
	Route::post('/terapias/solicitar/{user}', 'TerapiaController@solicitar')->name('terapias.solicitar');
	Route::post('/terapias/sugerir/{user}', 'TerapiaController@sugerir')->name('terapias.sugerir');
	Route::get('/atenciones/ver/{user}', 'AtencionesController@verAtenciones')->name('atenciones.ver');
	// Route::get('/user/terapia/{id}', 'TerapiaController@userupdate')->name('terapia.userupdate');
	Route::get('/user/{id}/formulario', 'UserController@formulario')->name('user.formulario');
	Route::post('/user/{id}/solicitud-terapeuta', 'UserController@solicita')->name('user.solicita');
	Route::get('/user/descripcion/{id}', 'UserController@descripcion')->name('user.descripcion');
	Route::get('/user/descripcion/update/{id}', 'UserController@descripcionupdate')->name('user.descripcionupdate');
	Route::get('/comentarios/user/{id}/', 'ComentariosController@showuser')->name('comentarios.showuser');
	Route::get('/comentarios/terapeuta/{id}/', 'ComentariosController@showterapeuta')->name('comentarios.showterapeuta');
	Route::get('/notificaciones', 'NotificacionesController@index')->name('notificaciones');
	Route::get('/notificaciones/{id}/dismiss', 'NotificacionesController@dismiss')->name('notificaciones.dismiss');
	Route::get('/comentarios/user/crea/{id}', 'ComentariosController@comentar')->name('comentarios.comentar');
	Route::get('/comentarios/terapeuta/crea/{id}', 'ComentariosController@comentaterapeuta')->name('comentarios.comentaterapeuta');
	Route::post('/comentarios/user/store/{id}', 'ComentariosController@guardar')->name('comentarios.guardar');
	Route::post('/comentarios/terapeuta/store/{id}', 'ComentariosController@guardarterapeuta')->name('comentarios.guardarterapeuta');
});

Route::group(['prefix'=> 'admin','middleware' => 'auth'], function(){
	Route::get('/noticias/listar', 'NoticiasController@listar')->name('noticias.listar');
	Route::get('/terapias/listar', 'TerapiaController@listar')->name('terapias.listar');
	Route::get('/terapias/{id}', 'TerapiaController@muestra')->name('terapias.muestra');
	Route::get('/terapeutas/{id}', 'UserController@verterapeuta')->name('users.verterapeuta');
	Route::get('/terapeutas/edit/{id}', 'UserController@adminedit')->name('users.adminedit');
	Route::get('/terapeutas/update/{id}', 'UserController@adminupdate')->name('users.adminupdate');
	Route::get('/terapeutas/destroy/{id}', 'UserController@admindestroy')->name('users.admindestroy');
	Route::get('/terapeutas', 'AdminController@terapeutas')->name('admin.terapeutas');
	Route::get('/usuarios', 'AdminController@usuarios')->name('admin.usuarios');
	Route::get('/terapias', 'AdminController@terapias')->name('admin.terapias');
	Route::get('/user/{id}', 'UserController@show')->name('admin.user.show');
	Route::get('/palabras/terapias', 'AdminController@showPalabrasTerapias')->name('sintomas.index');
	Route::post('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/palabras/terapias/add', 'AdminController@PalabrasTerapias')->name('admin.palabras');
	Route::get('/terapia/asignar/{id}', 'AdminController@verAgregaTerapia')->name('admin.verasigna');
	Route::post('/terapia/asigna/{id}', 'AdminController@AgregaTerapia')->name('admin.asigna');
});

Route::group(['prefix'=> 'perfil','middleware' => 'auth'], function(){
	Route::get('/{id}/comentarios', 'ComentariosController@show')->name('perfil.comentarios');
	Route::get('/{id}/terapias', 'TerapiaController@show')->name('perfil.terapias');
	Route::get('/{id}/horario', 'ScheduleController@show')->name('perfil.horario');
	Route::get('/{id}/agendamiento/{terapia}', 'AtencionesController@index')->name('perfil.hora');
	Route::get('/{id}/{terapia}', 'TerapiaController@ver')->name('perfil.miterapia');
});

Route::group(['prefix'=> 'search','middleware' => 'auth'], function(){
	Route::post('/','SearchController@index')->name('search');
	Route::get('/','SearchController@index')->name('search');
	Route::get('/terapia/{id}/show','SearchController@showterapia')->name('search.showterapia');
	Route::get('/terapeuta/{id}/show','PerfilController@show')->name('search.showterapeuta');
	Route::post('/sugerencia','SearchController@sugerencia')->name('search.sugerencia');
});

Auth::routes();

app/Noticias.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticias extends Model
{
    
}

app/Http/Controllers/NoticiasController.php
<?php

namespace App\Http\Controllers;

use App\Noticias;
use Illuminate\Http\Request;

class NoticiasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();

        $array['user'] = $user;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.menu_noticias',[
            'user' => $user,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()->user();

        $array['user'] = $user;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.crear_noticias',[
            'user' => $user,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if ($request->hasFile('imagen')){
            $filenameWithExt = $request->file('imagen')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt,PATHINFO_FILENAME);
            $extension = $request->file('imagen')->getClientOriginalExtension();
            $fileNameToStore = date('Y-m-d_H-i-s') . '_' . uniqid() . '_noticia' . '.' .$extension;
            request()->imagen->move(public_path('imagenes/noticias/'), $fileNameToStore);
        } else {
            $fileNameToStore = "default.png";
        }

        $noticia = new Noticias;
        $noticia->titulo = $request->titulo;
        $noticia->detalle = $request->detalle;
        $noticia->fecha = $request->fecha;
        $noticia->extracto = $request->extracto;
        $noticia->imagen = $fileNameToStore;

        $noticia->save();

        $user = auth()->user();
        $mensaje = 'Noticia registrada exitosamente';

        $array['user'] = $user;
        $array['mensaje'] = $mensaje;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias',[
            'user' => $user,
            'mensaje' => $mensaje,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $noticia = Noticias::find($id);
        $user = auth()->user();

        $array['user'] = $user;
        $array['noticia'] = $noticia;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.show',[
            'user' => $user,
            'noticia' => $noticia
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $noticia = Noticias::find($id);
        $user = auth()->user();

        $array['user'] = $user;
        $array['noticia'] = $noticia;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.edit',[
            'user' => $user,
            'noticia' => $noticia
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $noticia = Noticias::find($id);
        $noticia->titulo = $request->titulo;
        $noticia->extracto = $request->extracto;
        $noticia->detalle = $request->detalle;
        if ($request->hasFile('imagen')){
            $filenameWithExt = $request->file('imagen')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt,PATHINFO_FILENAME);
            $extension = $request->file('imagen')->getClientOriginalExtension();
            $fileNameToStore = date('Y-m-d_H-i-s') . '_' . uniqid() . '_noticia' . '.' .$extension;
            request()->imagen->move(public_path('imagenes/noticias/'), $fileNameToStore);
            $noticia->imagen = $fileNameToStore;
        }

        $noticia->save();

        $user = auth()->user();
        $mensaje = 'Noticia actualizada exitosamente.';

        $array['user'] = $user;
        $array['noticia'] = $noticia;
        $array['mensaje'] = $mensaje;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.show',[
            'user' => $user,
            'noticia' => $noticia,
            'mensaje' => $mensaje,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $noticia = Noticias::find($id);
        $noticia->delete();

        $user = auth()->user();
        $noticias = Noticias::all();
        $mensaje = 'Noticia eliminada exitosamente.';

        $array['user'] = $user;
        $array['noticias'] = $noticias;
        $array['mensaje'] = $mensaje;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.lista',[
            'user' => $user,
            'noticias' => $noticias,
            'mensaje' => $mensaje,
        ]);
    }

    public function listar()
    {
        $user = auth()->user();
        $noticias = Noticias::all();

        $array['user'] = $user;
        $array['noticias'] = $noticias;

        if ( request()->wantsJson() ) {
            return $array;
        }

        return view('perfiles.admin.noticias.lista',[
            'user' => $user,
            'noticias' => $noticias
        ]);
    }
}

resources/views/perfiles/admin/noticias/crear_noticias.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Crear una Noticia</h3>
		</div>
		<form role="form" method="POST" action="{{ route('noticias.store') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="titulo">Titulo de la Noticia</label>
					<input 
						name="titulo" 
						type="text" 
						class="form-control" 
						id="titulo" 
						placeholder="Ingresa el Titulo de la Noticia" 
						required
					>
				</div>
				<div class="form-group">
					<label for="detalle">Detalle de la Noticia</label>
					<textarea 
						name="detalle" 
						type="textarea"
						class="form-control" 
						id="detalle" 
						placeholder="Ingresa el Detalle de la Noticia" 
						required
					></textarea>
				</div>				
				<div class="form-group">
					<label for="fecha">Fecha de la Noticia</label>
					<input 
						name="fecha" 
						type="date" 
						class="form-control" 
						id="fecha" 
					>
				</div>
				<div class="form-group">
					<label for="imagen">Imagen de la Noticia</label>
					<input 
						name="imagen" 
						type="file" 
						class="form-control" 
						id="imagen" 
					>
				</div>
			</div>
			<div class="box-footer">
				<button type="submit" class="btn btn-success">Crear Noticia</button>
				<a class="btn btn-secondary" href="javascript:history.back()">Volver</a>
			</div>
		</form>
	</div>
</div>

{{-- <script src="../../bower_components/ckeditor/ckeditor.js"></script> --}}

@endsection

resources/views/perfiles/admin/noticias/edit.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="box box-primary">
		<div class="row">
			<div class="box-header with-border col-8 align-left">
				<h3 class="box-title">Actualizar Noticia</h3>
			</div>
		</div>
		<form role="form" method="POST" action="{{ route('noticias.update', $noticia) }}" enctype="multipart/form-data">
			{{ method_field('PUT') }}
			{{ csrf_field() }}
			<div class="box-body">
				<div class="form-group">
					<label for="titulo">Titulo</label>
					<input 
						name="titulo" 
						type="text" 
						class="form-control" 
						id="titulo" 
						placeholder="Ingresa el titulo" 
						value="{{ $noticia->titulo }}"
					>
				</div>
				<div class="form-group">
					<label for="extracto">Extracto</label>
					<input 
						name="extracto" 
						type="text" 
						class="form-control" 
						id="extracto" 
						placeholder="Ingresa el extracto" 
						value="{{ $noticia->extracto }}"
					>
				</div>
				<div class="form-group">
					<label for="detalle">Detalle</label>
					<input 
						name="detalle" 
						type="text" 
						class="form-control" 
						id="detalle" 
						placeholder="Ingresa el detalle" 
						value="{{ $noticia->detalle }}"
					>
				</div>
				<div class="form-group">
					<label for="imagen">Imagen de la Noticia</label>
					<input name="imagen" type="file" id="imagen">
				</div>
			</div>
			<div class="box-footer p-2">
				<button type="submit" class="btn btn-success">Actualizar</button>
			</div>
		</form>
	</div>
</div>

@endsection

resources/views/perfiles/admin/noticias/lista.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	@if(isset($noticias))
		@foreach($noticias as $noticia)
			<a href="{{ route('noticias.show', $noticia) }}">
				<div class="row border bg-secondary rounded" style="margin-left: 10px; margin-right: 10px; margin-bottom: 10px;">
					<div class="col-12">
						<div class="row">
							<div class="col-4 align-middle">
								<img src="/imagenes/noticias/{{$noticia->imagen}}" alt="Noticia-{{$noticia->id}}" class="img-fluid rounded"/>
							</div>
							<div class="col-5">
								<h5 class="text-primary">{{ $noticia->titulo }}</h5>
								<p>{{ $noticia->extracto }}</p>
							</div>
							<div class="col-3">
								@if(isset($noticia->created_at))
									<small>{{ $noticia->created_at->format('d-m-Y') }}</small>
								@endif
							</div>
						</div>
					</div>
				</div>
			</a>
		@endforeach
	@else
		<div class="card text-center">
	      	<div class="card-body">
	        	<h5 class="card-title">No existen noticias.</h5>
	      	</div>
    	</div>
	@endif
</div>

@endsection

resources/views/perfiles/admin/noticias/show.blade.php
@extends('layout')

@section('title', 'Perfil')

@section('content')

@include('perfiles.parcial')

@if(isset($mensaje))
	<div class="container alert alert-success alert-dismissible">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<h4><i class="icon fa fa-check"></i> {{ $mensaje }} </h4>
	</div>
@endif

<div class="container">
	<div class="container">
		<div class="d-flex row justify-content-center">
			<div class="col-12 d-flex">
				<div class="card" style="width: 18rem;">
					<img src="/imagenes/noticias/{{$noticia->imagen}}" alt="Noticia-{{$noticia->id}}" class="card-img-top rounded img-fluid"/>
					<div class="card-body text-center">
						<h5 class="card-title">{{ $noticia->titulo }}</h5>
						<p class="card-text">{{ $noticia->detalle }}</p>
						<a href="{{ route('noticias.edit', $noticia) }}" type="button" class="btn btn-secondary btn-lg btn-block">Editar Noticia</a>
						<form method="POST" action="{{ route('noticias.destroy', $noticia) }}">
							{{ method_field('DELETE') }}
							{{ csrf_field() }}
							<button type="submit" class="btn btn-secondary btn-lg btn-block">Eliminar Noticia</button>
						</form>
						<a href="{{ route('noticias.listar') }}" type="button" class="btn btn-secondary btn-lg btn-block">Volver</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection